language: groovy
sudo: false
cache:
  directories:
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/wrapper"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
jdk:
- oraclejdk8
install: true
script: "./travis-build.sh"
env:
  global:
  - GIT_NAME="Robert Oschwald"
  - GIT_EMAIL="robertoschwald@gmail.com"
  - secure: QgwDKgm+TFRpt6fnAjbI4MGmBOIqfCm0ycyIom927aZPvhp4fzzI6wGIN06RTAPNao95BnV7TwSgonRExPfqIMCrMzDj4BXVYkK9uXUXTUPYw24+9cEv2ZvnyEurg/MR2ajpu3MHtam+7uGO8mh4pYq+693RpiU+IZFkB5vPWcM=
  - secure: mRX4Ye6O4iHcxV48DD8Oaz+7FmrN7vMf67g3Ym24zfzLLaxbl77z0XCMQYblU4s/OBqP9BNo4Y7v6HzCxJyWwMIRqz9txk/DkUUAzTSYHIxQwJqnZTdZNjh9muVmvGuyyBj7z/IhBtKVhNDEXn+OW6f0tdiHeLnaAy6kAovvwCA=
  - secure: gUh+JJotMsLdmblcDwnOK+EWXtd7C44b2TX2rXTOyZbS8pw6Ocs6Y54LYhJJ4CKY+799otBIYl8pTqPnnF+GqdnGu/1Brn7bUqADBBdROF+T93OKZa1nWFm4Pt/2ejX6ZeZCwfZwguVfyPBkUAOZAxMqIsD+QnPPUDMTqTQ0pyZt6vKoIMKwEd9NF6XVFN+XBkBj8LGJH8B26nPd6JYVvoftOGZRZOupesCBITehxJFTec+awgUpuoshe+zl7TgViIXJIY9PWsX0pKddqEixAxNoUqeyLH+I+8qZMGIDnFt5jGpS8iuURz5+xb9JuEB6k/8O7HJzlDJtOioYQUNfnMYnW08OKPuBMOAPkyM062ab2j1VbKf6q8yC83WWAjdbRJotCwrfRBj0vm5TR3szUkjSSv/GtDdI7Rh8iXQIZxry4P7kFRsq5F6BtQQMJqUMHLNyPU5xcPudTGSAeKYYrHuLmXIB3CSkBEAIO2uyUl6Gze9MZkef4bobd2mcunoCswdikwbSfweV2JeXcxyP2KJNgVDYBTBZkJRlb6PJWJNjKyDzQFiwAXwUmsfIby8y2gpEIOblh+Se/dnUJNHcmLFQbyCZ7RcT/vP2MrcYnY74doTXVcOU+lFk1mDw9jRb/7/AwlzhYN1a4t0z00uersdk6Mj2Ay941m06VGbUGyY=
