[[installation]]
== Installation

To use the plugin, you must have the grails-schwartz plugin already installed in your project.

=== "`Install`" the plugin by adding it to build.gradle

Add a dependency for the plugin by adding it to the `dependencies` block in build.gradle.

Note:

The groupId of the plugin artefact has changed with version 2.0.3 from org.grails.plugins to io.github.robertoschwald.

```groovy
dependencies {
   compile 'io.github.robertoschwald:schwartz-monitor:{project-version}'
}
```

=== URL Mapping controller
The plugin does not provide a default URL-Mapping for the plugins QuartzController, so you are free to map it as you like.
For this, you must add a url mapping to your URLMappings.groovy file:

```groovy
"/quartz/$action?"(controller:"quartz")
```

=== Securing the Controller

If you use a security plugin (Spring-Security-Core, etc), you must ensure the controller methods are secured. E.g. when using Spring-Security-Core, add a rule to application.groovy or runtime.groovy which is appropriate for your security needs:

```groovy
grails {
  plugin {
    springsecurity {
       interceptUrlMap = [
          ...
          [pattern:'/quartz/**',              access:['ROLE_ADMIN']]
          ...
       }
    }
  }
}
```

